"""Baseline schema as shipped before the Phase 0 truthfulness work.

Existing installations created by Base.metadata.create_all can adopt
migrations with:  python -m alembic stamp 0001_baseline

baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-20 22:29:57.483328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('proposed_action', sa.JSON(), nullable=False),
    sa.Column('safety_validation', sa.JSON(), nullable=False),
    sa.Column('execution_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_decisions_intersection_id'), ['intersection_id'], unique=False)

    op.create_table('ai_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('training_dataset', sa.String(length=128), nullable=True),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)

    op.create_table('corridors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordination_mode', sa.String(length=32), nullable=True),
    sa.Column('cycle_length_sec', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('health_metrics', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('requested_phase', sa.Integer(), nullable=True),
    sa.Column('safety_clearance_passed', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('technician_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('lane_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('occupancy_pct', sa.Float(), nullable=True),
    sa.Column('avg_speed_kph', sa.Float(), nullable=True),
    sa.Column('quality', sa.String(length=32), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_observations_intersection_id'), ['intersection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_observations_timestamp'), ['timestamp'], unique=False)

    op.create_table('transit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=True),
    sa.Column('priority_requested', sa.Boolean(), nullable=True),
    sa.Column('priority_granted', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vehicle_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('speed_kph', sa.Float(), nullable=True),
    sa.Column('dwell_time_sec', sa.Float(), nullable=True),
    sa.Column('trajectory', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kph', sa.Float(), nullable=True),
    sa.Column('visibility_meters', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('road_condition', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_observations_timestamp'), ['timestamp'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('intersections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=64), nullable=True),
    sa.Column('operational_status', sa.String(length=32), nullable=True),
    sa.Column('corridor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('intersections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intersections_code'), ['code'], unique=True)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approaches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('road_name', sa.String(length=128), nullable=False),
    sa.Column('speed_limit_kph', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cameras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('stream_url', sa.String(length=255), nullable=False),
    sa.Column('stream_status', sa.String(length=32), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('detection_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_frame_timestamp', sa.DateTime(), nullable=True),
    sa.Column('calibration_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('affected_lanes', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_detected_at'), ['detected_at'], unique=False)

    op.create_table('sensors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('lane_id', sa.String(length=36), nullable=True),
    sa.Column('sensor_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('telemetry_endpoint', sa.String(length=255), nullable=True),
    sa.Column('health_status', sa.String(length=32), nullable=True),
    sa.Column('last_observation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('quality', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_controllers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('connection_status', sa.String(length=32), nullable=True),
    sa.Column('control_mode', sa.String(length=32), nullable=True),
    sa.Column('active_phase', sa.Integer(), nullable=True),
    sa.Column('current_phase_start', sa.DateTime(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('fallback_mode', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intersection_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=True),
    sa.Column('flow_rate_vph', sa.Float(), nullable=True),
    sa.Column('occupancy_pct', sa.Float(), nullable=True),
    sa.Column('avg_speed_kph', sa.Float(), nullable=True),
    sa.Column('queue_length_meters', sa.Float(), nullable=True),
    sa.Column('avg_wait_time_sec', sa.Float(), nullable=True),
    sa.Column('traffic_pressure', sa.Float(), nullable=True),
    sa.Column('data_quality', sa.String(length=32), nullable=True),
    sa.Column('calculation_method', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_metrics_intersection_id'), ['intersection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_metrics_timestamp'), ['timestamp'], unique=False)

    op.create_table('lanes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('approach_id', sa.String(length=36), nullable=False),
    sa.Column('lane_number', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('assigned_phase', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approach_id'], ['approaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('controller_id', sa.String(length=36), nullable=False),
    sa.Column('requested_phase', sa.Integer(), nullable=False),
    sa.Column('command_type', sa.String(length=32), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('safety_check_passed', sa.Boolean(), nullable=True),
    sa.Column('safety_report', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('controller_acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['signal_controllers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('signal_phases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('controller_id', sa.String(length=36), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('ring', sa.Integer(), nullable=True),
    sa.Column('barrier', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('min_green', sa.Integer(), nullable=True),
    sa.Column('max_green', sa.Integer(), nullable=True),
    sa.Column('yellow_change', sa.Integer(), nullable=True),
    sa.Column('red_clearance', sa.Integer(), nullable=True),
    sa.Column('ped_walk', sa.Integer(), nullable=True),
    sa.Column('ped_clearance', sa.Integer(), nullable=True),
    sa.Column('conflicting_phases', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['signal_controllers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_w', sa.Float(), nullable=False),
    sa.Column('bbox_h', sa.Float(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('lane_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_detections_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_detections_timestamp'))

    op.drop_table('vehicle_detections')
    op.drop_table('signal_phases')
    op.drop_table('signal_commands')
    op.drop_table('lanes')
    with op.batch_alter_table('traffic_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_traffic_metrics_intersection_id'))

    op.drop_table('traffic_metrics')
    op.drop_table('signal_controllers')
    op.drop_table('sensors')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_detected_at'))

    op.drop_table('incidents')
    op.drop_table('cameras')
    op.drop_table('approaches')
    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('intersections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intersections_code'))

    op.drop_table('intersections')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_observations_timestamp'))

    op.drop_table('weather_observations')
    op.drop_table('vehicle_tracks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('transit_events')
    with op.batch_alter_table('traffic_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_observations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_traffic_observations_intersection_id'))

    op.drop_table('traffic_observations')
    op.drop_table('maintenance_events')
    op.drop_table('knowledge_documents')
    op.drop_table('emergency_events')
    op.drop_table('devices')
    op.drop_table('corridors')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))

    op.drop_table('alerts')
    op.drop_table('ai_models')
    with op.batch_alter_table('ai_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_decisions_intersection_id'))
        batch_op.drop_index(batch_op.f('ix_ai_decisions_created_at'))

    op.drop_table('ai_decisions')
    # ### end Alembic commands ###
